version: "3.7"

services:
  server:
    container_name: server
    build:
      context: ./server
      target: development
      dockerfile: Dockerfile.dev
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    restart: on-failure
    command: npm run start:dev
    env_file:
      - ./server/.env
    environment:
      FUN_TRANSLATIONS_API_KEY: ${FUN_TRANSLATIONS_API_KEY}
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "4000:4000"
    environment:
      PORT: ${CLIENT_PORT}
    restart: on-failure
    command: npm run start
    stdin_open: true
    tty: true
    env_file:
      - ./client/.env
    depends_on:
      - server
